=== sumithomas25/week5/emp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Company">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Employee" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Emp-name" type="xs:string"/>
							<xs:element name="Emp-age" type="xs:integer"/>
							<xs:element name="Emp-salary" type="msi0"/>
							<xs:element name="Emp-emailid" type="msi1"/>
							<xs:element name="Emp-Phonenum" type="msi2"/>
							<xs:element name="Emp-designation" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name='EMPID' type="xs:ID" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="msi0">
		<xs:restriction base="xs:integer">
			<xs:minExclusive value="50000"/>
			<xs:maxExclusive value="200000"/>
		</xs:restriction>
	</xs:simpleType>
	
</xs:schema>

=== sumithomas25/week5/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="emp.xsl"?>
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="emp.xsd">
	<Employee EMPID="Emp00">
		<Emp-name>Adriel Luis Gomes</Emp-name>
		<Emp-age>56</Emp-age>
		<Emp-salary>55000</Emp-salary>
		<Emp-emailid>adre@gmail.com</Emp-emailid>
		<Emp-Phonenum>9099123932</Emp-Phonenum>
		<Emp-designation>CEO</Emp-designation>
	</Employee>
	<Employee EMPID="Emp01">
		<Emp-name>Sumi Thomas</Emp-name>
		<Emp-age>27</Emp-age>
		<Emp-salary>77000</Emp-salary>
		<Emp-emailid>samieboi@gmail.com</Emp-emailid>
		<Emp-Phonenum>7989139645</Emp-Phonenum>
		<Emp-designation>Junior Developer</Emp-designation>
	</Employee>
	<Employee EMPID="Emp02">
		<Emp-name>Adity Raghavan</Emp-name>
		<Emp-age>43</Emp-age>
		<Emp-salary>100000</Emp-salary>
		<Emp-emailid>adi123@gmail.com</Emp-emailid>
		<Emp-Phonenum>9822123214</Emp-Phonenum>
		<Emp-designation>Software Engineer</Emp-designation>
	</Employee>
	<Employee EMPID="Emp03">
		<Emp-name>Delwin Thomas</Emp-name>
		<Emp-age>34</Emp-age>
		<Emp-salary>70000</Emp-salary>
		<Emp-emailid>dlthomas@gmail.com</Emp-emailid>
		<Emp-Phonenum>9791239225</Emp-Phonenum>
		<Emp-designation>Senior Developer</Emp-designation>
	</Employee>
</Company>
